window.TRUST_DATA = {
  villages: [
    ["Andarkulam", "ஆண்டார்குளம்", "திரு. முருகேசன்", "+97430347772"],
    ["Uchipatti", "உச்சிபத்தை", "திரு. மாரியப்பன்", "+919994690273"],
    ["Melakalangal", "மேலகலங்கல்", "திரு. திருமலை குமார்", "+919791701261"],
    ["Vellalankulam", "வெள்ளாளங்குளம்", "திரு. சண்முகவேல்", "+919940688040"],
    ["Uthanakulam", "உத்தான்குளம்", "திரு. அன்னை மகாலிங்கம்", "+919578827371"],
    ["Velayuthapuram", "வேலாயுதபுரம்", "திரு. மகேந்திரன்", "+919626417816"],
    ["Balapathirapuram", "பலபத்திராமபுரம்", "திரு. தங்கமகாராஜன்", "+96895646567"],
    ["Ramakrishnapuram", "ராமகிருஷ்ணாபுரம்", "திரு. ஜெகன் பாபு தம்பார்", "+917619623832"],
    ["Sarkaraikulam", "சர்க்கரைக்குளம்", "திரு. பெ. மாரிமுருகன்", "+918754755733"],
    ["Poovalingapuram", "பூவலிங்கபுரம்", "திரு. கஜேந்திவரதப் பெருமாள்", "+916374970741"],
    ["Maruthathalpuram", "மருதாத்தாள்புரம்", "திரு. பெருமாள்சாமி", "+919943972296"],
    ["Arunachalapuram", "அருணாச்சலபுரம்", "திரு. பொன்னுச்சாமி", "+919600432212"],
    ["Amuthapuram", "அமுதாபுரம்", "திரு. சமுத்திர பாண்டியன்", "+919047071275"],
    ["South Pattadaikatti", "தெற்கு பட்டாடைக்கட்டி", "திரு. கிருஷ்ணசாமி", "+919345702754"],
    ["North Pattadaikatti", "வடக்கு பட்டாடைக்கட்டி", "திரு. சுப்பிரமணியன்", "+919787843478"],
    ["Pottipuram", "பொட்டிபுரம்", "திரு. ராஜா", "+96893613784"],
    ["Sevalasamuthiram", "சீவலசமுத்திரம்", "திரு. செல்வகுமார்", "+916381972663"],
    ["Karaikandarkulam", "கரைகண்டார்குளம்", "திரு. செல்வதுரை", "+919884506353"]
  ],
  missions: [
    ["🎓", "Education Support", "கல்வி உதவி", "Scholarships, school support, higher education guidance and help for students who lost parental support.", "உதவித்தொகை, பள்ளி உதவி, உயர் கல்வி வழிகாட்டுதல் மற்றும் பெற்றோர் ஆதரவை இழந்த மாணவர்களுக்கு உதவி."],
    ["🏥", "Healthcare", "சுகாதாரம்", "Medical camps, blood donation, health awareness and emergency support.", "மருத்துவ முகாம், இரத்த தானம், சுகாதார விழிப்புணர்வு மற்றும் அவசர உதவி."],
    ["💼", "Employment Guidance", "வேலைவாய்ப்பு வழிகாட்டுதல்", "Career guidance, private job support and overseas employment guidance through community networks.", "வேலை வழிகாட்டுதல், தனியார் வேலை உதவி மற்றும் சமூக வலையமைப்புகள் மூலம் வெளிநாட்டு வேலைவாய்ப்பு வழிகாட்டுதல்."],
    ["📚", "Government Exam Coaching", "அரசு தேர்வு பயிற்சி", "TNPSC and other government job coaching awareness for educated youth.", "படித்த இளைஞர்களுக்கான TNPSC மற்றும் பிற அரசு வேலை தேர்வு பயிற்சி விழிப்புணர்வு."],
    ["🌱", "Agriculture Development", "விவசாய மேம்பாடு", "Farmer meetings, modern farming awareness and government subsidy guidance.", "விவசாயிகள் கூட்டம், நவீன விவசாய விழிப்புணர்வு மற்றும் அரசு மானியம் வழிகாட்டுதல்."],
    ["🌳", "Green Village", "பசுமை கிராமம்", "Tree plantation, clean village campaigns and plastic-free village awareness.", "மரக்கன்று நடுதல், தூய்மை கிராமம் மற்றும் பிளாஸ்டிக் இல்லா கிராம விழிப்புணர்வு."],
    ["💧", "Water Conservation", "நீர் பாதுகாப்பு", "Rainwater harvesting, water tanker support and village water management awareness.", "மழைநீர் சேகரிப்பு, தண்ணீர் டேங்கர் ஆதரவு மற்றும் கிராம நீர் மேலாண்மை விழிப்புணர்வு."],
    ["👩", "Women Empowerment", "பெண்கள் முன்னேற்றம்", "Self-help groups, tailoring, entrepreneurship and financial awareness.", "சுய உதவி குழுக்கள், தையல், தொழில்முனைவு மற்றும் நிதி விழிப்புணர்வு."],
    ["👦", "Youth Development", "இளைஞர் மேம்பாடு", "Leadership, sports, volunteer programs and digital literacy.", "தலைமைத்துவம், விளையாட்டு, தன்னார்வ நிகழ்ச்சிகள் மற்றும் டிஜிட்டல் அறிவு."]
  ],
  activities: [
    ["Medical Camps", "மருத்துவ முகாம்கள்"],
    ["Education Awareness", "கல்வி விழிப்புணர்வு"],
    ["Career Guidance", "வேலைவாய்ப்பு வழிகாட்டுதல்"],
    ["Government Coaching", "அரசு தேர்வு பயிற்சி"],
    ["Scholarship Distribution", "உதவித்தொகை வழங்குதல்"],
    ["Tree Plantation", "மரக்கன்று நடுதல்"],
    ["Agriculture Meetings", "விவசாய கூட்டங்கள்"],
    ["Women Empowerment", "பெண்கள் முன்னேற்றம்"],
    ["Village Cleaning", "கிராம தூய்மை"],
    ["Food Distribution", "உணவு வழங்குதல்"],
    ["Blood Donation", "இரத்த தானம்"],
    ["Skill Development", "திறன் மேம்பாடு"]
  ],
  tools: [
    ["Membership records", "உறுப்பினர் பதிவுகள்"],
    ["Village-wise members", "கிராம வாரியான உறுப்பினர்கள்"],
    ["Volunteer dashboard", "தன்னார்வ டாஷ்போர்டு"],
    ["Donation reports", "நன்கொடை அறிக்கைகள்"],
    ["Scholarship applications", "கல்வி உதவி விண்ணப்பங்கள்"],
    ["Activity updates", "செயல்பாட்டு புதுப்பிப்புகள்"],
    ["Gallery upload", "புகைப்பட பதிவேற்றம்"],
    ["Excel export", "எக்செல் ஏற்றுமதி"]
  ],
  translations: {
    en: {
      "a11y.skip": "Skip to content",
      "nav.about": "About",
      "nav.villages": "18 Villages",
      "nav.activities": "Activities",
      "nav.gallery": "Gallery",
      "nav.join": "Join Us",
      "nav.donate": "Donate",
      "nav.contact": "Contact",
      "hero.eyebrow": "Registered rural development trust in Tenkasi District",
      "hero.copy": "18 Villages. One Community. One Vision. Together for education, rural development and social empowerment.",
      "cta.donate": "Donate Now",
      "cta.volunteer": "Become Volunteer",
      "cta.member": "Join Member",
      "stats.villages": "Villages",
      "stats.members": "Members",
      "stats.students": "Students Supported",
      "stats.families": "Families Helped",
      "stats.volunteers": "Volunteers",
      "stats.activities": "Activities",
      "mission.eyebrow": "Our Work",
      "mission.title": "Mission Areas",
      "mission.copy": "Focused support for education, health, employment, agriculture, environment, women, youth and village development.",
      "about.eyebrow": "About the Trust",
      "about.title": "A community trust built by villages, for villages.",
      "about.copy": "The trust works to organize village coordinators, grow membership, maintain transparent accounts, support students and families, and improve life across the 18 villages.",
      "about.president": "President",
      "about.secretary": "Secretary",
      "about.treasurer": "Treasurer",
      "about.advisor": "Advisor",
      "timeline.eyebrow": "Trust Timeline",
      "timeline.title": "Important Decisions",
      "timeline.t1.title": "Reorganization meeting",
      "timeline.t1.copy": "Leadership and members discussed strengthening the trust, forming coordinators and improving community service.",
      "timeline.t2.title": "Membership and coordination plan",
      "timeline.t2.copy": "Each village planned one coordinator, ten joint coordinators, annual membership, ID cards and transparent reports.",
      "timeline.t3.title": "Asset and tanker review",
      "timeline.t3.copy": "The trust reviewed the water tanker status and discussed recovery or repayment into the trust account.",
      "villages.eyebrow": "Our Villages",
      "villages.title": "18 Villages Covered",
      "villages.copy": "Every village has a coordinator to identify needs, support members, and keep communication active.",
      "search.label": "Search",
      "search.placeholder": "Search village or coordinator",
      "activities.eyebrow": "Activities",
      "activities.title": "Service Programs",
      "gallery.eyebrow": "Gallery",
      "gallery.title": "Community Moments",
      "gallery.banner": "Trust community gathering",
      "gallery.logo": "Trust identity",
      "gallery.note.title": "Gallery ready",
      "gallery.note.copy": "Education, medical camp, meeting, agriculture, tree plantation and village event photos can be added here from Google Drive.",
      "donate.eyebrow": "Donation",
      "donate.title": "Support Rural Development",
      "donate.copy": "Your contribution helps education support, medical camps, food assistance, village development and emergency help.",
      "donate.memberTitle": "Membership / Donation Account",
      "donate.note": "Trust bank account details can be updated after official bank approval.",
      "membership.eyebrow": "Join Our Trust",
      "membership.title": "Membership Registration",
      "membership.copy": "Submit your details to create a membership record. The form is ready for Google Apps Script integration.",
      "form.name": "Full Name",
      "form.guardian": "Father / Guardian Name",
      "form.mobile": "Mobile Number",
      "form.whatsapp": "WhatsApp Number",
      "form.gender": "Gender",
      "form.dob": "Date of Birth",
      "form.email": "Email",
      "form.occupation": "Occupation",
      "form.education": "Education",
      "form.village": "Village",
      "form.blood": "Blood Group",
      "form.volunteerInterest": "Volunteer Interest",
      "form.address": "Current Address",
      "form.submit": "Submit Membership",
      "volunteer.eyebrow": "Volunteer",
      "volunteer.title": "Become a Volunteer",
      "volunteer.availability": "Availability",
      "volunteer.skills": "Skills / Preferred Activity",
      "volunteer.submit": "Submit Volunteer Details",
      "app.eyebrow": "Web Application",
      "app.title": "Admin and Member Tools",
      "contact.eyebrow": "Contact",
      "contact.title": "Reach the Trust Office",
      "footer.tagline": "Together We Build Strong Villages.",
      "bottom.home": "Home",
      "bottom.villages": "Villages",
      "bottom.join": "Join",
      "bottom.call": "Contact",
      "chat.placeholder": "Ask about membership, donation, office..."
    },
    ta: {
      "a11y.skip": "உள்ளடக்கத்துக்கு செல்லவும்",
      "nav.about": "அறிமுகம்",
      "nav.villages": "18 கிராமங்கள்",
      "nav.activities": "செயல்பாடுகள்",
      "nav.gallery": "புகைப்படங்கள்",
      "nav.join": "சேருங்கள்",
      "nav.donate": "நன்கொடை",
      "nav.contact": "தொடர்பு",
      "hero.eyebrow": "தென்காசி மாவட்டத்தில் பதிவு செய்யப்பட்ட ஊரக வளர்ச்சி அறக்கட்டளை",
      "hero.copy": "18 கிராமங்கள். ஒரு சமூகம். ஒரு நோக்கம். கல்வி, ஊரக வளர்ச்சி மற்றும் சமூக முன்னேற்றத்திற்காக ஒன்றிணைவோம்.",
      "cta.donate": "நன்கொடை அளிக்க",
      "cta.volunteer": "தன்னார்வலராக",
      "cta.member": "உறுப்பினராக சேர",
      "stats.villages": "கிராமங்கள்",
      "stats.members": "உறுப்பினர்கள்",
      "stats.students": "மாணவர்கள் உதவி",
      "stats.families": "குடும்பங்கள் உதவி",
      "stats.volunteers": "தன்னார்வலர்கள்",
      "stats.activities": "செயல்பாடுகள்",
      "mission.eyebrow": "எங்கள் பணி",
      "mission.title": "முக்கிய சேவை துறைகள்",
      "mission.copy": "கல்வி, சுகாதாரம், வேலைவாய்ப்பு, விவசாயம், சுற்றுச்சூழல், பெண்கள், இளைஞர்கள் மற்றும் கிராம வளர்ச்சிக்கான ஆதரவு.",
      "about.eyebrow": "அறக்கட்டளை பற்றி",
      "about.title": "கிராம மக்களால், கிராம மக்களுக்காக உருவான சமூக அறக்கட்டளை.",
      "about.copy": "ஒருங்கிணைப்பாளர்களை அமைத்தல், உறுப்பினர் வளர்ச்சி, வெளிப்படையான கணக்கு, மாணவர்கள் மற்றும் குடும்பங்களுக்கு உதவி, 18 கிராமங்களின் முன்னேற்றம் ஆகியவற்றில் அறக்கட்டளை செயல்படுகிறது.",
      "about.president": "தலைவர்",
      "about.secretary": "செயலாளர்",
      "about.treasurer": "பொருளாளர்",
      "about.advisor": "ஆலோசகர்",
      "timeline.eyebrow": "அறக்கட்டளை வரலாறு",
      "timeline.title": "முக்கிய முடிவுகள்",
      "timeline.t1.title": "மறுசீரமைப்பு கூட்டம்",
      "timeline.t1.copy": "அறக்கட்டளையை வலுப்படுத்தல், ஒருங்கிணைப்பாளர்களை அமைத்தல் மற்றும் சமூக சேவையை மேம்படுத்தல் குறித்து ஆலோசிக்கப்பட்டது.",
      "timeline.t2.title": "உறுப்பினர் மற்றும் ஒருங்கிணைப்பு திட்டம்",
      "timeline.t2.copy": "ஒவ்வொரு கிராமத்திற்கும் ஒருங்கிணைப்பாளர், பத்து இணை ஒருங்கிணைப்பாளர்கள், வருட சந்தா, உறுப்பினர் அட்டை மற்றும் வெளிப்படையான அறிக்கைகள் திட்டமிடப்பட்டது.",
      "timeline.t3.title": "சொத்து மற்றும் டேங்கர் ஆய்வு",
      "timeline.t3.copy": "தண்ணீர் டேங்கர் நிலை மற்றும் மீட்பு அல்லது தொகை செலுத்துதல் குறித்து கலந்தாய்வு செய்யப்பட்டது.",
      "villages.eyebrow": "எங்கள் கிராமங்கள்",
      "villages.title": "18 கிராமங்கள்",
      "villages.copy": "ஒவ்வொரு கிராமத்திலும் தேவைகளை கண்டறிந்து, உறுப்பினர்களுக்கு உதவி செய்து, தொடர்பை செயலில் வைத்திருக்க ஒருங்கிணைப்பாளர் உள்ளார்.",
      "search.label": "தேடல்",
      "search.placeholder": "கிராமம் அல்லது ஒருங்கிணைப்பாளர் தேடவும்",
      "activities.eyebrow": "செயல்பாடுகள்",
      "activities.title": "சேவை திட்டங்கள்",
      "gallery.eyebrow": "புகைப்படங்கள்",
      "gallery.title": "சமூக தருணங்கள்",
      "gallery.banner": "அறக்கட்டளை சமூக கூட்டம்",
      "gallery.logo": "அறக்கட்டளை அடையாளம்",
      "gallery.note.title": "புகைப்பட பகுதி தயார்",
      "gallery.note.copy": "கல்வி, மருத்துவ முகாம், கூட்டம், விவசாயம், மரக்கன்று நடுதல் மற்றும் கிராம நிகழ்ச்சி புகைப்படங்களை Google Drive மூலம் இங்கு சேர்க்கலாம்.",
      "donate.eyebrow": "நன்கொடை",
      "donate.title": "ஊரக வளர்ச்சிக்கு ஆதரவு அளிக்கவும்",
      "donate.copy": "உங்கள் பங்களிப்பு கல்வி உதவி, மருத்துவ முகாம், உணவு உதவி, கிராம வளர்ச்சி மற்றும் அவசர உதவிக்கு பயன்படும்.",
      "donate.memberTitle": "உறுப்பினர் / நன்கொடை கணக்கு",
      "donate.note": "அதிகாரப்பூர்வ வங்கி அனுமதி கிடைத்த பிறகு அறக்கட்டளையின் வங்கி விவரங்கள் புதுப்பிக்கலாம்.",
      "membership.eyebrow": "அறக்கட்டளையில் சேருங்கள்",
      "membership.title": "உறுப்பினர் பதிவு",
      "membership.copy": "உறுப்பினர் பதிவை உருவாக்க உங்கள் விவரங்களை சமர்ப்பிக்கவும். இந்த படிவம் Google Apps Script இணைப்புக்கு தயார்.",
      "form.name": "முழு பெயர்",
      "form.guardian": "தந்தை / பாதுகாவலர் பெயர்",
      "form.mobile": "மொபைல் எண்",
      "form.whatsapp": "WhatsApp எண்",
      "form.gender": "பாலினம்",
      "form.dob": "பிறந்த தேதி",
      "form.email": "மின்னஞ்சல்",
      "form.occupation": "தொழில்",
      "form.education": "கல்வி",
      "form.village": "கிராமம்",
      "form.blood": "இரத்த வகை",
      "form.volunteerInterest": "தன்னார்வ ஆர்வம்",
      "form.address": "தற்போதைய முகவரி",
      "form.submit": "உறுப்பினர் பதிவு சமர்ப்பிக்க",
      "volunteer.eyebrow": "தன்னார்வம்",
      "volunteer.title": "தன்னார்வலராக சேருங்கள்",
      "volunteer.availability": "கிடைக்கும் நேரம்",
      "volunteer.skills": "திறன்கள் / விருப்பமான செயல்",
      "volunteer.submit": "தன்னார்வ விவரம் சமர்ப்பிக்க",
      "app.eyebrow": "வலை பயன்பாடு",
      "app.title": "நிர்வாக மற்றும் உறுப்பினர் கருவிகள்",
      "contact.eyebrow": "தொடர்பு",
      "contact.title": "அறக்கட்டளை அலுவலகத்தை தொடர்பு கொள்ளுங்கள்",
      "footer.tagline": "ஒன்றிணைந்து வலுவான கிராமங்களை உருவாக்குவோம்.",
      "bottom.home": "முகப்பு",
      "bottom.villages": "கிராமங்கள்",
      "bottom.join": "சேர",
      "bottom.call": "தொடர்பு",
      "chat.placeholder": "உறுப்பினர், நன்கொடை, அலுவலகம் பற்றி கேளுங்கள்..."
    }
  }
};
